apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_HOST: postgres-database
  POSTGRES_DB: chatbox
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: baki@Hanma